# Production overrides for docker-compose.yml
# This file is automatically merged with docker-compose.yml when running docker compose
version: '3.8'

services:
  frontend:
    environment:
      # Use relative API URL so it works through Cloudflare tunnel
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_WS_URL=/ws
    build:
      args:
        - NEXT_PUBLIC_API_URL=/api
        - NEXT_PUBLIC_WS_URL=/ws

  api:
    environment:
      # Add Cloudflare tunnel URL to CORS origins
      - CORS_ORIGINS=http://localhost:3000,https://*.trycloudflare.com,https://fraudguard.mohankrishna.site

